filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - C:\\Path\\Input\\input_file_test.log
    start_position: beginning

output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]